slogan: ""

menu:
  - title: 首页
    url: 
    intro: "贴吧FE内部首页"
    icon: "fa fa-paw"
  - title: 工具 
    url: tools
    intro: "项目集"
    icon: "fa fa-th-large"
  - title: 存档
    url: archives
    intro: "全部文章"
    icon: "fa fa-list"
  - title: 分类 
    url: categories
    intro: "所有分类"
    icon: "fa fa-folder"
  # - title: Tags
  #   url: tags
  #   intro: "All the tags."
  #   icon: "fa fa-tags"
  - title: 关于
    url: about
    intro: "简介"
    icon: "fa fa-info-circle"
  - title: RSS
    url: atom.xml
    intro: "订阅"
    icon: "fa fa-rss"

links:
  - title: 贴吧FE WiKi
    url: http://wiki.baidu.com/pages/viewpage.action?pageId=30638799
    intro: "百度贴吧FE团队WiKi主页"
    icon: "fa fa-code"
  - title: "source"
    url: http://www.github.com/wzpan
    intro: "My Github account."
    icon: "fa fa-github"

widgets:
# - search
- category
# - tagcloud
- recent_posts  
- links

rss: 
fancybox: false
favicon: favicon.png
google_analytics: 